
/*===========================================================
 Retail Business Analytics Platform
 Database : PostgreSQL
 Table    : customer
===========================================================*/

------------------------------------------------------------
-- Q1. What is the total revenue generated by male vs female customers?
------------------------------------------------------------

SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


------------------------------------------------------------
-- Q2. Which customers used a discount but still spent
-- more than the average purchase amount?
------------------------------------------------------------

SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >=
(
    SELECT AVG(purchase_amount)
    FROM customer
);


------------------------------------------------------------
-- Q3. Which are the top 5 products with the highest average rating?
------------------------------------------------------------

SELECT item_purchased,
       ROUND(AVG(review_rating::numeric),2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;


------------------------------------------------------------
-- Q4. Compare average purchase amount between
-- Standard and Express shipping.
------------------------------------------------------------

SELECT shipping_type,
       ROUND(AVG(purchase_amount),2) AS average_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


------------------------------------------------------------
-- Q5. Compare subscribers vs non-subscribers.
------------------------------------------------------------

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS average_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


------------------------------------------------------------
-- Q6. Top 5 products with highest discount usage.
------------------------------------------------------------

SELECT item_purchased,
ROUND(
100.0 *
SUM(CASE
WHEN discount_applied='Yes'
THEN 1
ELSE 0
END)
/
COUNT(*)
,2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


------------------------------------------------------------
-- Q7. Customer Segmentation
------------------------------------------------------------

WITH customer_type AS
(
SELECT
customer_id,
previous_purchases,

CASE

WHEN previous_purchases=1
THEN 'New'

WHEN previous_purchases BETWEEN 2 AND 10
THEN 'Returning'

ELSE 'Loyal'

END
AS customer_segment

FROM customer

)

SELECT
customer_segment,
COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment;


------------------------------------------------------------
-- Q8. Top 3 products within each category.
------------------------------------------------------------

WITH item_counts AS
(
SELECT
category,
item_purchased,
COUNT(*) AS total_orders,

ROW_NUMBER()
OVER
(
PARTITION BY category
ORDER BY COUNT(*) DESC
)
AS rank

FROM customer

GROUP BY category,item_purchased

)

SELECT *
FROM item_counts
WHERE rank<=3;


------------------------------------------------------------
-- Q9. Are repeat buyers more likely to subscribe?
------------------------------------------------------------

SELECT
subscription_status,
COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;


------------------------------------------------------------
-- Q10. Revenue contribution by Age Group.
------------------------------------------------------------

SELECT

CASE

WHEN age<20
THEN 'Below 20'

WHEN age BETWEEN 20 AND 29
THEN '20-29'

WHEN age BETWEEN 30 AND 39
THEN '30-39'

WHEN age BETWEEN 40 AND 49
THEN '40-49'

ELSE '50+'

END
AS age_group,

SUM(purchase_amount) AS revenue

FROM customer

GROUP BY age_group

ORDER BY revenue DESC;


------------------------------------------------------------
-- Q11. Revenue by Location.
------------------------------------------------------------

SELECT
location,
SUM(purchase_amount) AS revenue
FROM customer
GROUP BY location
ORDER BY revenue DESC;


------------------------------------------------------------
-- Q12. Revenue by Payment Method.
------------------------------------------------------------

SELECT
payment_method,
COUNT(*) AS total_orders,
SUM(purchase_amount) AS revenue
FROM customer
GROUP BY payment_method
ORDER BY revenue DESC;


------------------------------------------------------------
-- Q13. Average Purchase by Season.
------------------------------------------------------------

SELECT
season,
ROUND(AVG(purchase_amount),2) AS average_purchase
FROM customer
GROUP BY season
ORDER BY average_purchase DESC;


------------------------------------------------------------
-- Q14. Highest Rated Category.
------------------------------------------------------------

SELECT
category,
ROUND(AVG(review_rating::numeric),2) AS average_rating
FROM customer
GROUP BY category
ORDER BY average_rating DESC;


------------------------------------------------------------
-- Q15. Top 10 Highest Spending Customers.
------------------------------------------------------------

SELECT
customer_id,
SUM(purchase_amount) AS total_spent
FROM customer
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;


------------------------------------------------------------
-- Q16. Rank Customers by Total Spending.
------------------------------------------------------------

SELECT
customer_id,
SUM(purchase_amount) AS total_spent,

RANK()
OVER
(
ORDER BY SUM(purchase_amount) DESC
)
AS customer_rank

FROM customer

GROUP BY customer_id;


------------------------------------------------------------
-- Q17. Most Purchased Color.
------------------------------------------------------------

SELECT
color,
COUNT(*) AS total_sales
FROM customer
GROUP BY color
ORDER BY total_sales DESC;


------------------------------------------------------------
-- Q18. Most Purchased Size.
------------------------------------------------------------

SELECT
size,
COUNT(*) AS total_sales
FROM customer
GROUP BY size
ORDER BY total_sales DESC;


------------------------------------------------------------
-- Q19. Running Revenue (Window Function)
------------------------------------------------------------

SELECT
customer_id,
purchase_amount,

SUM(purchase_amount)
OVER
(
ORDER BY customer_id
)
AS running_revenue

FROM customer;


------------------------------------------------------------
-- Q20. Customers Spending Above Average.
------------------------------------------------------------

SELECT
customer_id,
purchase_amount
FROM customer
WHERE purchase_amount >
(
SELECT AVG(purchase_amount)
FROM customer
)
ORDER BY purchase_amount DESC;


------------------------------------------------------------
-- Q21. Dense Rank Customers.
------------------------------------------------------------

SELECT
customer_id,
purchase_amount,

DENSE_RANK()
OVER
(
ORDER BY purchase_amount DESC
)
AS dense_rank

FROM customer;


------------------------------------------------------------
-- Q22. Top 10 Selling Products.
------------------------------------------------------------

SELECT
item_purchased,
COUNT(*) AS total_sales
FROM customer
GROUP BY item_purchased
ORDER BY total_sales DESC
LIMIT 10;


------------------------------------------------------------
-- Q23. Frequency of Purchases.
------------------------------------------------------------

SELECT
frequency_of_purchases,
COUNT(*) AS total_customers
FROM customer
GROUP BY frequency_of_purchases
ORDER BY total_customers DESC;


------------------------------------------------------------
-- Q24. Average Purchase by Gender.
------------------------------------------------------------

SELECT
gender,
ROUND(AVG(purchase_amount),2) AS average_purchase
FROM customer
GROUP BY gender;


------------------------------------------------------------
-- Q25. Total Revenue Generated.
------------------------------------------------------------

SELECT
SUM(purchase_amount) AS total_revenue
FROM customer;